version: '3.5'
services:
  db:
    container_name: db
    image: postgres:latest
    env_file: ./db/database.conf
    ports:
      - 5432:5432  
    volumes:
      - ./db/data:/var/lib/postgresql

  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: bot
    env_file: ./bot/app.conf
    ports:
      - 5000:5000
    depends_on:
      - db
